[build]
  command = "bash ./scripts/netlify-build.sh"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

# Redirect all routes to the static HTML file
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 