[build]
  command = "bash ./scripts/netlify-build.sh"
  publish = "public"

[build.environment]
  PHP_VERSION = "8.2"
  NODE_VERSION = "18"
  APP_ENV = "production"
  APP_DEBUG = "false"
  DB_CONNECTION = "sqlite"
  DB_DATABASE = "/opt/build/repo/database/database.sqlite"
  CACHE_DRIVER = "array"
  SESSION_DRIVER = "array"
  QUEUE_DRIVER = "array"
  
# Explicitly telling Netlify to skip database operations during build
[context.production.environment]
  NETLIFY_USE_YARN = "true"
  SKIP_DB_OPERATIONS = "true"

# Netlify PHP function handlers
[functions]
  directory = "netlify/functions"

# Redirect all routes to the static HTML file
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 